/* ============================================================
   Lu Runtime — generated by luc (Lu Compiler)
   ============================================================ */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
/* Lu global argc/argv */
int   __luc_argc = 0;
char **__luc_argv = NULL;

/* ── Lu types ── */
typedef struct { uint8_t a, b, c, d; uint16_t port; } lu_ip_t;
typedef struct { int *vals; int len; }                  lu_cor_t;
typedef struct { char *data; int len; }                 lu_msg_t;
typedef struct { char nic[64]; char name[64]; lu_ip_t ip; } lu_user_t;
typedef struct { int id; char meta[256]; }              lu_server_t;
typedef struct { void **buf; int head, tail, cap; }     lu_chan_t;
typedef struct { char name[64]; void(*cb)(void*); }    lu_event_t;

/* ── Runtime error codes ── */
#define ERR_COR  1
#define ERR_IP   2
#define ERR_MEM  3
#define ERR_MSG  4
#define ERR_AUTH 5

/* ── Runtime functions ── */
static lu_ip_t lu_parse_ip(const char *s) {
    lu_ip_t ip = {0};
    sscanf(s, "%hhu.%hhu.%hhu.%hu", &ip.a, &ip.b, &ip.c, &ip.port);
    return ip;
}

static lu_cor_t lu_make_cor(int *vals, int len) {
    lu_cor_t c; c.vals = vals; c.len = len; return c;
}

static lu_user_t lu_user_new(const char *attrs) {
    lu_user_t u = {0}; strncpy(u.nic, attrs, 63); return u;
}

static lu_server_t *lu_server_new(int id, const char *meta) {
    lu_server_t *s = malloc(sizeof(lu_server_t));
    s->id = id; strncpy(s->meta, meta, 255); return s;
}

static void lu_send(const char *data, lu_ip_t *dest) {
    if (dest)
        printf("[Lu NET] send '%s' -> %d.%d.%d:%d\n",
               data, dest->a, dest->b, dest->c, dest->port);
    else
        printf("[Lu NET] send '%s'\n", data);
}

static void lu_recv(const char *expected) {
    printf("[Lu NET] recv '%s'\n", expected ? expected : "");
}

static void lu_broadcast(const char *data) {
    printf("[Lu NET] broadcast '%s'\n", data);
}

static void lu_route(lu_ip_t dst, lu_ip_t via) {
    printf("[Lu NET] route %d.%d.%d:%d via %d.%d.%d:%d\n",
           dst.a,dst.b,dst.c,dst.port,via.a,via.b,via.c,via.port);
}

static void lu_inq(const char *req) {
    printf("[Lu NET] inq: %s\n", req);
}

static void lu_log(const char *level, const char *msg) {
    const char *col = "\033[0m";
    if (!strcmp(level,"err")  || !strcmp(level,"fatal")) col="\033[31m";
    else if (!strcmp(level,"warn")) col="\033[33m";
    else if (!strcmp(level,"debug")) col="\033[36m";
    printf("%s[Lu %s]\033[0m %s\n", col, level, msg);
    if (!strcmp(level,"fatal")) exit(1);
}

static void lu_throw(int code, const char *msg) {
    fprintf(stderr, "[Lu THROW] code=%d: %s\n", code, msg);
    exit(code);
}

static void lu_assert(bool cond, const char *msg, int line) {
    if (!cond) {
        fprintf(stderr, "[Lu ASSERT] line %d: %s\n", line, msg);
        exit(1);
    }
}

static void lu_print_int(int64_t v)    { printf("%lld\n", (long long)v); }
static void lu_print_float(double v)   { printf("%g\n", v); }
static void lu_print_str(const char*v) { printf("%s\n", v ? v : ""); }
static void lu_print_bool(bool v)      { printf("%s\n", v?"true":"false"); }
#define lu_print(x) _Generic((x), \
    int:lu_print_int, int64_t:lu_print_int,\
    long long:lu_print_int, double:lu_print_float,\
    float:lu_print_float, bool:lu_print_bool,\
    char*:lu_print_str, default:lu_print_int)(x)

static void lu_spawn(void (*fn)(void)) { if (fn) fn(); }

static lu_chan_t *lu_chan_new(void) {
    lu_chan_t *c = calloc(1, sizeof(lu_chan_t));
    c->cap = 16; c->buf = malloc(sizeof(void*)*16); return c;
}
static void lu_chan_send(lu_chan_t *c, void *v) {
    if (!c) return; c->buf[c->tail % c->cap] = v; c->tail++;
}
static void *lu_chan_recv(lu_chan_t *c) {
    if (!c || c->head == c->tail) return NULL;
    return c->buf[c->head++ % c->cap];
}

static lu_event_t *lu_event_new(const char *name) {
    lu_event_t *e = calloc(1, sizeof(lu_event_t));
    strncpy(e->name, name, 63); return e;
}
static void lu_event_emit(lu_event_t *e, void *data) {
    if (e && e->cb) e->cb(data);
}
static void lu_event_on(lu_event_t *e, void(*cb)(void*)) {
    if (e) e->cb = cb;
}

static void __lu_trace(const char *what) {
    fprintf(stderr, "[Lu TRACE] %s\n", what);
}
static void __lu_breakpoint(int line) {
    fprintf(stderr, "[Lu BREAK] line %d\n", line);
}
static void __lu_watch(const char *var) {
    fprintf(stderr, "[Lu WATCH] %s changed\n", var);
}

/* ── cor/ verification ── */
static bool lu_cor_verify(lu_cor_t a, lu_cor_t b) {
    if (a.len != b.len) return false;
    for (int i = 0; i < a.len; i++)
        if (a.vals[i] != b.vals[i]) return false;
    return true;
}

/* ── IP helpers ── */
static bool lu_ip_eq(lu_ip_t a, lu_ip_t b) {
    return a.a==b.a && a.b==b.b && a.c==b.c && a.port==b.port;
}
static void lu_ip_print(lu_ip_t ip) {
    printf("%d.%d.%d:%d", ip.a, ip.b, ip.c, ip.port);
}

/* ── User helpers ── */
static void lu_user_set_name(lu_user_t *u, const char *name) {
    if (u && name) strncpy(u->name, name, 63);
}
static void lu_user_set_ip(lu_user_t *u, lu_ip_t ip) {
    if (u) u->ip = ip;
}
static void lu_user_print(lu_user_t u) {
    printf("User{nic='%s' name='%s' ip=%d.%d.%d:%d}\n",
           u.nic, u.name, u.ip.a, u.ip.b, u.ip.c, u.ip.port);
}

/* ── Chan grow ── */
static void lu_chan_grow(lu_chan_t *c) {
    int newcap = c->cap * 2;
    c->buf = realloc(c->buf, sizeof(void*) * newcap);
    c->cap = newcap;
}
/* safe chan_send with auto-grow */
static void lu_chan_send_safe(lu_chan_t *c, void *v) {
    if (!c) return;
    if (c->tail - c->head >= c->cap) lu_chan_grow(c);
    c->buf[c->tail % c->cap] = v;
    c->tail++;
}

/* Lu opt level: O2 */

#include "lu_self_runtime.h"

void _q1(void);

/* mode: server */
static const int MAX_SRC = 1048576;
static const int MAX_TOK = 65536;

void _q1(void) {
    printf("%s\n", "╔══════════════════════════════════════════════════════╗");
    printf("%s\n", "║  Lu Self-Hosting Compiler v1.0                      ║");
    printf("%s\n", "║  Written in Lu — compiles Lu → C                   ║");
    printf("%s\n", "╚══════════════════════════════════════════════════════╝");
    int argc_val = __luc_argc;
    if ((argc_val < 2)) {
        LUC_FPRINTF(stderr, "[LUC] Usage: luc_self <input.lu>\n");
        return;
    }
    char* infile = __luc_argv[1];
    LUC_FPRINTF(stderr, "[LUC] Compiling: %s\n", infile);
    char* src = malloc(MAX_SRC);
    int src_len = 0;
    char* fp = luc_fopen(infile, "rb");
    if ((fp == 0)) {
        LUC_FPRINTF(stderr, "[LUC] Error: cannot open '%s'\n", infile);
        return;
    }
    src_len = luc_fread(src, 1, MAX_SRC, fp);
    luc_fclose(fp);
    src[src_len] = 0;
    LUC_FPRINTF(stderr, "[LUC] Read: %d bytes\n", src_len);
    char* toks = calloc(MAX_TOK, 64);
    int ntok = 0;
    LUC_FPRINTF(stderr, "[LUC] Stage 1: Lexing...\n");
    ntok = lu_self_lex_cast(src, src_len, toks);
    LUC_FPRINTF(stderr, "[LUC] Tokens: %d\n", ntok);
    char* outname = malloc(512);
    snprintf(outname, 512, "%s.c", infile);
    char* ofp = luc_fopen(outname, "w");
    if ((ofp == 0)) {
        LUC_FPRINTF(stderr, "[LUC] Error: cannot write '%s'\n", outname);
        return;
    }
    LUC_FPRINTF(ofp, "/* Generated by Lu Self-Hosting Compiler v1.0 */\n");
    LUC_FPRINTF(ofp, "#include \\\"lu_self_runtime.h\\\"\n");
    LUC_FPRINTF(ofp, "\n");
    LUC_FPRINTF(ofp, "int   __luc_argc = 0;\n");
    LUC_FPRINTF(ofp, "char **__luc_argv = NULL;\n");
    LUC_FPRINTF(ofp, "\n");
    LUC_FPRINTF(stderr, "[LUC] Stage 2: Codegen...\n");
    lu_self_codegen_cast(ofp, toks, ntok);
    LUC_FPRINTF(ofp, "\nint main(int argc, char **argv) {\n");
    LUC_FPRINTF(ofp, "    __luc_argc = argc;\n");
    LUC_FPRINTF(ofp, "    __luc_argv = argv;\n");
    LUC_FPRINTF(ofp, "    _q1();\n");
    LUC_FPRINTF(ofp, "    return 0;\n");
    LUC_FPRINTF(ofp, "}\n");
    luc_fclose(ofp);
    LUC_FPRINTF(stderr, "[LUC] Written: %s\n", outname);
    LUC_FPRINTF(stderr, "[LUC] Build with:\n");
    LUC_FPRINTF(stderr, "      gcc -O2 -std=c11 -o luc_self %s\n", outname);
    LUC_FPRINTF(stderr, "[LUC] Done.\n");
    free(src);
    free(toks);
    free(outname);
}

int main(int argc, char **argv) {
    __luc_argc = argc; __luc_argv = argv;
    /* Lu entry point: call all #q blocks in order */
    _q1();
    return 0;
}
